import isaaclab.sim as sim_utils
from isaaclab.actuators import ActuatorNetMLPCfg, DCMotorCfg, ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg
from isaaclab.utils.assets import ISAACLAB_NUCLEUS_DIR
import math

"""
* :obj:`HRP5P_CFG`: HRP5 humanoid robot configuration.
"""
HRP5P_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=f"/home/hippolyte/HRP5Pmain/HRP5Pmain.usd",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=4,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.95),
        joint_pos={
            "RCY": 0.0,
            "RCR": 0.0,
            "RCP": math.radians(-26.87),
            "RKP": math.radians(50.0),
            "RAP": math.radians(-23.13),
            "RAR": 0.0,
            "LCY": 0.0,
            "LCR": 0.0,
            "LCP": math.radians(-26.87),
            "LKP": math.radians(50.0),
            "LAP": math.radians(-23.13),
            "LAR": 0.0,
            "WP": 0.0,
            "WR": 0.0,
            "WY": 0.0,
            "HP": 0.0,
            "HY": 0.0,
            "RSC": 0.0,
            "RSP": math.radians(60.0),
            "RSR": math.radians(-20.0),
            "RSY": math.radians(-5.0),
            "REP": math.radians(-105.0),
            "RWRY": 0.0,
            "RWRR": math.radians(-40.0),
            "RWRP": 0.0,
            "RHDY": 0.0,
            "LSC": 0.0,
            "LSP": math.radians(60.0),
            "LSR": math.radians(20.0),
            "LSY": math.radians(5.0),
            "LEP": math.radians(-105.0),
            "LWRY": 0.0,
            "LWRR": math.radians(40.0),
            "LWRP": 0.0,
            "LHDY": 0.0,
            "LTMP": math.radians(-60.5),
            "LTPIP": 0.0,
            "LTDIP": 0.0,
            "LMMP": math.radians(60.5),
            "LMPIP": 0.0,
            "LMDIP": 0.0,
            "LIMP": math.radians(60.5),
            "LIPIP": 0.0,
            "LIDIP": 0.0,
            "RTMP": math.radians(60.5),
            "RTPIP": 0.0,
            "RTDIP": 0.0,
            "RMMP": math.radians(-60.5),
            "RMPIP": 0.0,
            "RMDIP": 0.0,
            "RIMP": math.radians(-60.5),
            "RIPIP": 0.0,
            "RIDIP": 0.0,
        },
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[".*CY", ".*CR", ".*CP", ".*KP", ".*AP", ".*AR"],
            effort_limit=300,
            velocity_limit=100.0,
            stiffness={".*": 200.0},
            damping={".*": 5.0},
        ),
        "arms": ImplicitActuatorCfg(
            joint_names_expr=[".*SC", ".*SP", ".*SR", ".*SY", ".*EP", ".*WR[PYR]"],
            effort_limit=200,
            velocity_limit=100.0,
            stiffness={".*": 40.0},
            damping={".*": 10.0},
        ),
"""         "fingers": ImplicitActuatorCfg(
            joint_names_expr=[".*TMP", ".*PIP", ".*DIP", ".*IMP", ".*MMP", ".*MDIP", ".*IPIP", ".*IDIP"],
            effort_limit=50,
            velocity_limit=100.0,
            stiffness={".*": 10.0},
            damping={".*": 2.0},
        ), """ # WE DON'T NEED FINGERS FOR NOW
        "torso": ImplicitActuatorCfg(
            joint_names_expr=["WP", "WR", "WY"],# "HP", "HY"],
            effort_limit=100,
            velocity_limit=50.0,
            stiffness={".*": 20.0},
            damping={".*": 4.0},
        ),
    },
)
